<script setup lang="ts">
import { computed, ref } from "vue";
import { Eye, Pencil, Plus, Search, Trash2, Utensils, Flame, Dumbbell, Clock, X } from "lucide-vue-next";
import BaseBadge from "@/components/ui/BaseBadge.vue";
import NutritionPlanModal from "@/components/ui/NutritionPlanModal.vue";
import { nutritionPlans, type NutritionPlan } from "@/data/mock/nutritionPlans";

const list=ref<NutritionPlan[]>(structuredClone(nutritionPlans));
const search=ref(""); const status=ref<"All"|NutritionPlan["status"]>("All");
const modal=ref(false); const editing=ref<NutritionPlan|null>(null); const viewing=ref<NutritionPlan|null>(null); const deleting=ref<NutritionPlan|null>(null);
const filtered=computed(()=>{const q=search.value.trim().toLowerCase();return list.value.filter(p=>(!q||[p.name,p.clientName,p.trainerName,p.goal].some(v=>v.toLowerCase().includes(q)))&&(status.value==="All"||p.status===status.value))});
const stats=computed(()=>({total:list.value.length,active:list.value.filter(p=>p.status==="Active").length,draft:list.value.filter(p=>p.status==="Draft").length,completed:list.value.filter(p=>p.status==="Completed").length}));
const openCreate=()=>{editing.value=null;modal.value=true}; const openEdit=(p:NutritionPlan)=>{editing.value=structuredClone(p);modal.value=true};
const savePlan=(p:NutritionPlan)=>{const i=list.value.findIndex(x=>x.id===p.id);if(i>=0)list.value[i]=p;else list.value.unshift(p);modal.value=false};
const confirmDelete=()=>{if(deleting.value)list.value=list.value.filter(p=>p.id!==deleting.value!.id);deleting.value=null};
const badge=(s:NutritionPlan["status"])=>s==="Active"?"success":s==="Draft"?"warning":"info";
const totalFoods=(p:NutritionPlan)=>p.meals.reduce((s,m)=>s+m.foods.length,0);
const planTotal=(p:NutritionPlan,key:"calories"|"protein"|"carbs"|"fats")=>p.meals.reduce((s,m)=>s+m.foods.reduce((a,f)=>a+Number(f[key]||0),0),0);
</script>
<template>
<div class="space-y-7">
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-400">Client wellness</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Nutrition</h1><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Create, manage and review personalized nutrition plans.</p></div><button class="inline-flex items-center justify-center rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-slate-800 dark:bg-white dark:text-slate-900" @click="openCreate"><Plus :size="17" class="mr-2"/>Create Plan</button></div>
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div v-for="item in [{label:'Total Plans',value:stats.total,icon:Utensils},{label:'Active',value:stats.active,icon:Flame},{label:'Draft',value:stats.draft,icon:Clock},{label:'Completed',value:stats.completed,icon:Dumbbell}]" :key="item.label" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="flex items-center justify-between"><p class="text-xs font-medium text-slate-500 dark:text-slate-400">{{item.label}}</p><component :is="item.icon" :size="17" class="text-slate-400"/></div><p class="mt-2 text-2xl font-bold">{{item.value}}</p></div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="grid gap-3 lg:grid-cols-[1fr_180px]"><div class="relative"><Search :size="17" class="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input v-model="search" class="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-slate-400 dark:border-slate-700 dark:bg-slate-800 dark:text-white" placeholder="Search plans, clients, trainers..."/></div><select v-model="status" class="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800 dark:text-white"><option>All</option><option>Active</option><option>Draft</option><option>Completed</option></select></div></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm"><thead class="border-b border-slate-100 bg-slate-50/70 text-[10px] uppercase tracking-wider text-slate-400 dark:border-slate-800 dark:bg-slate-800/50"><tr><th class="px-5 py-3.5">Plan</th><th class="px-4 py-3.5">Client</th><th class="px-4 py-3.5">Trainer</th><th class="px-4 py-3.5">Goal</th><th class="px-4 py-3.5">Daily Target</th><th class="px-4 py-3.5">Duration</th><th class="px-4 py-3.5">Status</th><th class="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800"><tr v-for="p in filtered" :key="p.id" class="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td class="px-5 py-4"><p class="font-semibold">{{p.name}}</p><p class="mt-1 text-xs text-slate-400">{{p.meals.length}} meals · {{totalFoods(p)}} foods</p></td><td class="px-4 py-4">{{p.clientName}}</td><td class="px-4 py-4">{{p.trainerName}}</td><td class="px-4 py-4">{{p.goal}}</td><td class="px-4 py-4"><div class="font-semibold">{{p.dailyCalories}} kcal</div><div class="text-xs text-slate-400">P {{p.protein}}g · C {{p.carbs}}g · F {{p.fats}}g</div></td><td class="px-4 py-4">{{p.durationWeeks}} weeks</td><td class="px-4 py-4"><BaseBadge :variant="badge(p.status)">{{p.status}}</BaseBadge></td><td class="px-5 py-4"><div class="flex justify-end gap-1"><button class="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800" title="View" @click="viewing=p"><Eye :size="17"/></button><button class="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-900 dark:hover:bg-slate-800" title="Edit" @click="openEdit(p)"><Pencil :size="17"/></button><button class="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 dark:hover:bg-red-950/30" title="Delete" @click="deleting=p"><Trash2 :size="17"/></button></div></td></tr><tr v-if="!filtered.length"><td colspan="8" class="px-5 py-12 text-center text-sm text-slate-400">No nutrition plans match your filters.</td></tr></tbody></table></div></div>
<NutritionPlanModal :is-open="modal" :plan="editing" @close="modal=false" @save="savePlan"/>
<Teleport to="body"><div v-if="viewing" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4" @click.self="viewing=null"><div class="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-800 dark:bg-slate-900"><div class="sticky top-0 flex items-center justify-between border-b border-slate-100 bg-white/95 px-6 py-5 backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><div><h2 class="text-xl font-bold">{{viewing.name}}</h2><p class="mt-1 text-xs text-slate-400">{{viewing.clientName}} · {{viewing.trainerName}}</p></div><button class="rounded-lg p-2 hover:bg-slate-100 dark:hover:bg-slate-800" @click="viewing=null"><X :size="18"/></button></div><div class="space-y-6 p-6"><div class="grid grid-cols-2 gap-3 md:grid-cols-4"><div v-for="m in [{l:'Calories',v:viewing.dailyCalories+' kcal'},{l:'Protein',v:viewing.protein+' g'},{l:'Carbs',v:viewing.carbs+' g'},{l:'Fats',v:viewing.fats+' g'}]" :key="m.l" class="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p class="text-xs text-slate-400">{{m.l}}</p><p class="mt-1 text-lg font-bold">{{m.v}}</p></div></div><div v-for="meal in viewing.meals" :key="meal.id" class="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><div class="flex items-start justify-between"><div><h3 class="font-semibold">{{meal.mealName}}</h3><p class="text-xs text-slate-400">{{meal.time}} · {{meal.notes}}</p></div><span class="text-xs text-slate-500">{{planTotal({meals:[meal]} as NutritionPlan,'calories')}} kcal</span></div><div class="mt-4 divide-y divide-slate-100 dark:divide-slate-800"><div v-for="food in meal.foods" :key="food.id" class="grid grid-cols-[1fr_auto] gap-4 py-3"><div><p class="text-sm font-medium">{{food.name}}</p><p class="text-xs text-slate-400">{{food.quantity}}</p></div><div class="text-right text-xs text-slate-500">{{food.calories}} kcal · P {{food.protein}}g · C {{food.carbs}}g · F {{food.fats}}g</div></div></div></div></div></div></div></Teleport>
<Teleport to="body"><div v-if="deleting" class="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 p-4"><div class="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl dark:bg-slate-900"><h3 class="text-lg font-bold">Delete nutrition plan?</h3><p class="mt-2 text-sm text-slate-500 dark:text-slate-400">This will remove <strong>{{deleting.name}}</strong> from the current mock dataset.</p><div class="mt-6 flex justify-end gap-3"><button class="rounded-xl border border-slate-200 px-4 py-2 text-sm dark:border-slate-700" @click="deleting=null">Cancel</button><button class="rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white" @click="confirmDelete">Delete Plan</button></div></div></div></Teleport>
</div>
</template>